suppressPackageStartupMessages({
  library('tidyverse')
  library('ggforce')
  library('sf')
  library('rnaturalearth')
  library('rnaturalearthdata')
  # library('igraph')
  # library('ggraph')
})
source('analysis/utils.r')
source('analysis/data.r')
source('analysis/numeric.r')
source('analysis/plot.r')

X = load.sr.data()
Xi = X[X$RQi.ARTCD4.Any|X$RQi.ARTCD4.Any,]
# print(mean(Xi$risk & Xi$hiv.acute))
do.counts(X)
# do.distrs(X)
# do.tests(X)
# plot.ints.cooc.hh(X) %>% save.plot('ints-cooc-h-vs-h',width=5,height=5)
# plot.ints.cooc.hn(X) %>% save.plot('ints-cooc-h-vs-n',width=5,height=5)
# plot.ints.cooc.nn(X) %>% save.plot('ints-cooc-n-vs-n',width=5,height=5)
# plot.map.co(X)       %>% save.plot('map-n-vs-plhiv',width=5,height=4)
# plot.risk.cascade(X) %>% save.plot('risk-cascade')
# plot.ints.vs.pops(X) %>% save.plot('ints-vs-pops',width=10,heigh=6)
