suppressPackageStartupMessages({
  library('tidyverse')
  library('ggforce')
  library('sf')
  library('rnaturalearth')
  library('rnaturalearthdata')
  library('viridis')
  library('geepack')
  # library('coefplot')
})
source('analysis/meta.r')
source('analysis/utils.r')
source('analysis/data.r')
source('analysis/numeric.r')
source('analysis/plot.r')

X = load.main.data(api.include=c('Y','x'))
numeric.main(X)
plot.map.co(X,size='Studies',fill='PLHIV') %>% save.plot('map-n-vs-plhiv',width=7,height=6)

XA = load.api.data(X)
numeric.api(XA)
q() # TEMP
plot.api.list(XA)
plot.api.list(XA,drop=TRUE,'Risk')
plot.distr.list(X)
save.plot.lists()
